# Generated by Django 2.0.3 on 2018-03-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_gamification', '0013_auto_20180324_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gamification.GamificationInterface')),
            ],
        ),
    ]
